# theme: jekyll-theme-hacker
title: renya's homepage
description: Bookmark this to keep an eye on my project updates!
theme: jekyll-theme-basically-basic
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
